export const SAMPLE_SIZE = 21 // pixels in image space (odd so it centers nicely)
export const VIEWER_HEIGHT = 350

export const styles = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px',
    width: '100%',
    boxSizing: 'border-box',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: '12px',
    width: 'min(90vw, 420px)',
  },
  title: {
    margin: 0,
    fontSize: 'clamp(20px, 4vw, 28px)',
    fontWeight: 600,
    textAlign: 'center',
    color: '#1a1a1a',
  },
  input: {
    padding: '12px 14px',
    borderRadius: '10px',
    border: '1px solid #c7c7c7',
    fontSize: '16px',
    width: '100%',
    boxSizing: 'border-box',
  },
  inputWithPreview: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    width: '100%',
  },
  button: {
    padding: '12px 14px',
    borderRadius: '10px',
    border: '1px solid #1a1a1a',
    backgroundColor: '#1a1a1a',
    color: '#ffffff',
    fontSize: '16px',
    cursor: 'pointer',
    width: '100%',
  },
  result: {
    margin: '8px 0 0 0',
    fontSize: '18px',
    fontWeight: 500,
    textAlign: 'center',
    color: '#1a1a1a',
  },
  imageUploadContainer: {
    width: '100%',
  },
  imageUploadLabel: {
    display: 'block',
    padding: '12px 14px',
    borderRadius: '10px',
    border: '2px dashed #c7c7c7',
    fontSize: '16px',
    textAlign: 'center',
    cursor: 'pointer',
    backgroundColor: '#f9f9f9',
    transition: 'all 0.2s',
    color: '#1a1a1a',
  } as React.CSSProperties,
  fileInput: {
    display: 'none',
  },
  imageViewerContainer: {
    width: '100%',
    position: 'relative',
    height: `${VIEWER_HEIGHT}px`,
    borderRadius: '10px',
    border: '2px solid #e0e0e0',
    overflow: 'hidden',
    cursor: 'grab',
    userSelect: 'none',
    touchAction: 'none',
  } as React.CSSProperties,
  imageViewerContainerGrabbing: {
    cursor: 'grabbing',
  } as React.CSSProperties,
  viewerCanvas: {
    display: 'block',
  } as React.CSSProperties,
  samplingOverlay: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    border: '2px solid rgba(255, 255, 255, 0.9)',
    boxShadow: '0 0 0 1px rgba(0, 0, 0, 0.5), inset 0 0 0 1px rgba(0, 0, 0, 0.3)',
    borderRadius: '2px',
    pointerEvents: 'none',
  } as React.CSSProperties,
  viewerHint: {
    margin: 0,
    fontSize: '14px',
    color: '#666',
    fontStyle: 'italic',
    textAlign: 'center',
  },
  sampleButton: {
    padding: '10px 14px',
    borderRadius: '10px',
    border: '1px solid #4a90d9',
    backgroundColor: '#4a90d9',
    color: '#ffffff',
    fontSize: '15px',
    cursor: 'pointer',
    width: '100%',
  },
} as const
