export const VIEWER_HEIGHT = 350

export const styles = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px',
    width: '100%',
    boxSizing: 'border-box',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: '12px',
    width: 'min(90vw, 420px)',
  },
  title: {
    margin: 0,
    fontSize: 'clamp(20px, 4vw, 28px)',
    fontWeight: 600,
    textAlign: 'center',
    color: '#1a1a1a',
  },
  button: {
    padding: '12px 14px',
    borderRadius: '10px',
    border: '1px solid #1a1a1a',
    backgroundColor: '#1a1a1a',
    color: '#ffffff',
    fontSize: '16px',
    cursor: 'pointer',
    width: '100%',
  },
  imageUploadContainer: {
    width: '100%',
  },
  imageUploadLabel: {
    display: 'block',
    padding: '12px 14px',
    borderRadius: '10px',
    border: '2px dashed #c7c7c7',
    fontSize: '16px',
    textAlign: 'center',
    cursor: 'pointer',
    backgroundColor: '#f9f9f9',
    transition: 'all 0.2s',
    color: '#1a1a1a',
  } as React.CSSProperties,
  fileInput: {
    display: 'none',
  },
  imageViewerContainer: {
    width: '100%',
    position: 'relative',
    height: `${VIEWER_HEIGHT}px`,
    borderRadius: '10px',
    border: '3px solid #1a1a1a',
    overflow: 'hidden',
    cursor: 'grab',
    userSelect: 'none',
    touchAction: 'none',
    backgroundColor: '#f0f0f0',
  } as React.CSSProperties,
  imageViewerContainerGrabbing: {
    cursor: 'grabbing',
  } as React.CSSProperties,
  viewerCanvas: {
    display: 'block',
  } as React.CSSProperties,
  viewerHint: {
    margin: 0,
    fontSize: '14px',
    color: '#666',
    fontStyle: 'italic',
    textAlign: 'center',
  },
  colorResult: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    padding: '12px 14px',
    borderRadius: '10px',
    border: '1px solid #e0e0e0',
    backgroundColor: '#f9f9f9',
    width: '100%',
    boxSizing: 'border-box',
  } as React.CSSProperties,
  colorResultSwatch: {
    width: '56px',
    height: '56px',
    borderRadius: '8px',
    border: '2px solid #e0e0e0',
    flexShrink: 0,
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
  } as React.CSSProperties,
  colorResultText: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  } as React.CSSProperties,
  colorResultHex: {
    fontSize: '15px',
    fontWeight: 600,
    color: '#1a1a1a',
    fontFamily: 'monospace',
    letterSpacing: '0.05em',
  } as React.CSSProperties,
  colorResultName: {
    fontSize: '18px',
    fontWeight: 500,
    color: '#444',
  } as React.CSSProperties,
  modeToggleRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '0px',
  } as React.CSSProperties,
  modeToggleButton: {
    padding: '6px 16px',
    fontSize: '14px',
    cursor: 'pointer',
    border: '1px solid #c7c7c7',
    backgroundColor: '#f9f9f9',
    color: '#444',
    userSelect: 'none',
    transition: 'all 0.15s',
  } as React.CSSProperties,
  modeToggleButtonSelected: {
    padding: '6px 16px',
    fontSize: '14px',
    cursor: 'pointer',
    border: '1px solid #1a1a1a',
    backgroundColor: '#1a1a1a',
    color: '#ffffff',
    userSelect: 'none',
    transition: 'all 0.15s',
  } as React.CSSProperties,
  colorResultSkeleton: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    padding: '12px 14px',
    borderRadius: '10px',
    border: '1px solid #e0e0e0',
    backgroundColor: '#f9f9f9',
    width: '100%',
    boxSizing: 'border-box',
  } as React.CSSProperties,
  skeletonSwatch: {
    width: '56px',
    height: '56px',
    borderRadius: '8px',
    flexShrink: 0,
    background: 'linear-gradient(90deg, #e8e8e8 25%, #f4f4f4 50%, #e8e8e8 75%)',
    backgroundSize: '800px 100%',
    animation: 'shimmer 1.4s ease-in-out infinite',
  } as React.CSSProperties,
  skeletonLines: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    flex: 1,
  } as React.CSSProperties,
  skeletonLineShort: {
    height: '14px',
    width: '80px',
    borderRadius: '4px',
    background: 'linear-gradient(90deg, #e8e8e8 25%, #f4f4f4 50%, #e8e8e8 75%)',
    backgroundSize: '800px 100%',
    animation: 'shimmer 1.4s ease-in-out infinite',
  } as React.CSSProperties,
  skeletonLineLong: {
    height: '18px',
    width: '140px',
    borderRadius: '4px',
    background: 'linear-gradient(90deg, #e8e8e8 25%, #f4f4f4 50%, #e8e8e8 75%)',
    backgroundSize: '800px 100%',
    animation: 'shimmer 1.4s ease-in-out infinite',
  } as React.CSSProperties,
} as const
